// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkxzblfqcsebqgvuhizh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBreHpibGZxY3NlYnFndnVoaXpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NjUwNTYsImV4cCI6MjA2MTM0MTA1Nn0.Ia9SprOFy2B7EmVHJrnwTkvaiGAovAdZu9kXr6WDUbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);